name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: pulumi-yamltube
          repository: mchaynes/pulumi-yamltube
      - run: |
          pushd pulumi-yamltube && make provider && popd
      - run: echo "${{ github.workspace }}/pulumi-yamltube/bin" >> $GITHUB_PATH
      - uses: pulumi/actions@v3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          command: up
          stack-name: dev
